In [1]:
from sklearn.preprocessing import Binarizer
import numpy as np
import pandas as pd

In [2]:
# list
X = [[1, 2, 3, 4, 2.5],
     [5, 4, 3, 2, 1],
     [3, 3, 3, 3, 3],
     [1, 1, 1, 1, 1]]
binarizer = Binarizer(threshold=2.5, copy=True)
res = binarizer.transform(X)
print(res)
print(X)  # 原始值并不变化,如果希望变化需要增加参数

[[0. 0. 1. 1. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]
[[1, 2, 3, 4, 2.5], [5, 4, 3, 2, 1], [3, 3, 3, 3, 3], [1, 1, 1, 1, 1]]


In [3]:
# np
X = [[1, 2, 3, 4, 5],
     [5, 4, 3, 2, 1]]
x = np.array(X)
binarizer = Binarizer(threshold=3)
res = binarizer.transform(x)
res

array([[0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0]])

In [4]:
# dataFrame
data = pd.read_csv("iris.data", header=None)
x = data.iloc[:, 2]
print(x.values)
binarizer = Binarizer(threshold=3.0)
res = binarizer.transform(x.values.reshape(-1, 1))  # transform 接收二维的数组
res

[1.4 1.4 4.7 4.3 5.2 5.4]


array([[0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [5]:
x

0    1.4
1    1.4
2    4.7
3    4.3
4    5.2
5    5.4
Name: 2, dtype: float64