In [1]:
from sklearn.preprocessing import Binarizer
import numpy as np
import pandas as pd

In [2]:
# list
X = [[1,2,3,4,5],
     [5,4,3,2,1],
     [3,3,3,3,3],
     [1,1,1,1,1]]
binarizer = Binarizer(threshold=2.5)
res = binarizer.transform(X)
print(res)
print(X) # 原始值并不变化,如果希望变化需要增加参数

[[0 0 1 1 1]
 [1 1 1 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]]
[[1, 2, 3, 4, 5], [5, 4, 3, 2, 1], [3, 3, 3, 3, 3], [1, 1, 1, 1, 1]]


In [3]:
# np
X = [[1, 2, 3, 4, 5],
     [5, 4, 3, 2, 1]]
x = np.array(X)
binarizer = Binarizer(threshold=3)
res = binarizer.transform(x)
res

array([[0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0]])

In [7]:
# dataFrame
data = pd.read_csv("iris.data", header=None)
x = data.iloc[:, 2]
print(x)
binarizer = Binarizer(threshold=3.0)
res = binarizer.transform(x)
res

0    1.4
1    1.4
2    4.7
3    4.3
4    5.2
5    5.4
Name: 2, dtype: float64


E:\software\anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[0., 0., 1., 1., 1., 1.]])

In [8]:
x

0    1.4
1    1.4
2    4.7
3    4.3
4    5.2
5    5.4
Name: 2, dtype: float64