In [1]:
import numpy as np
import pandas as pd

## 1 pd.get_dummies

In [2]:
!type car.data

vhigh,vhigh,2
med,high,3
low,low,5more


In [3]:
data = pd.read_csv('car.data', header=None, names=['feature1', 
                                                   'feature2', 
                                                   'feature3'])
data = data.iloc[:, [1, 2]]

In [4]:
feature2 = data['feature2']
feature2

0    vhigh
1     high
2      low
Name: feature2, dtype: object

In [5]:
# get_dummies 是利用pandas实现单列数据的one hot encode的方式
t = pd.get_dummies(feature2)
t

high  low  vhigh
0     0    0      1
1     1    0      0
2     0    1      0

In [6]:
# 对整个dataFrame实现one-hot编码
x = pd.DataFrame()
for col in data.columns:
    t = pd.get_dummies(data[col])
    t = t.rename(columns=lambda x: col + '_' + str(x))
    x = pd.concat((x, t), axis=1)

print(x.shape)
x.head()

(3, 6)


feature2_high  feature2_low  feature2_vhigh  feature3_2  feature3_3  \
0              0             0               1           1           0   
1              1             0               0           0           1   
2              0             1               0           0           0   

   feature3_5more  
0               0  
1               0  
2               1

## 2 sklearn.preprocessing.OneHotEncoder
#### 只能编码数字 不能编码字符串  所以作用不大

In [7]:
from sklearn.preprocessing import OneHotEncoder

X = np.array([[1,2,3,4,5],
              [5,4,3,2,1],
              [3,3,3,3,3]])
print("before transform:\n",X)
encoder=OneHotEncoder(sparse=False)
encoder.fit(X)
print("\n\nactive_features_:",encoder.active_features_)
print("\n\nfeature_indices_:",encoder.feature_indices_)
print("\n\nn_values_:",encoder.n_values_)
print("\n\nafter transform:",encoder.transform( [[1,2,3,4,4]]))

before transform:
 [[1 2 3 4 5]
 [5 4 3 2 1]
 [3 3 3 3 3]]


active_features_: [ 1  3  5  8  9 10 14 17 18 19 21 23 25]


feature_indices_: [ 0  6 11 15 20 26]


n_values_: [6 5 4 5 6]


after transform: [[1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.]]


## 3  label_binarize
主要用于对y进行one hot编码

In [11]:
from sklearn.preprocessing import label_binarize

data = pd.read_csv('car.data', header=None, names=['fea1', 'fea2', 'fea3'])
data = data.iloc[:, [1, 2]]
data

fea2   fea3
0  vhigh      2
1   high      3
2    low  5more

In [12]:
feature2 = data['fea2']
feature2

0    vhigh
1     high
2      low
Name: fea2, dtype: object

In [13]:
data2 = label_binarize(feature2, classes=['vhigh', 'high', 'low'])
data2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])