In [11]:
import numpy as np
import pandas as pd
x = pd.DataFrame([[1, 2, 3],
                  [4, 5, 6],
                  [10, 20, 30]])

### 最小-最大标准化

In [12]:
# 自己实现
xScalaMinMax = (x - x.min()) / (x.max() - x.min())
xScalaMinMax

0         1         2
0  0.000000  0.000000  0.000000
1  0.333333  0.166667  0.111111
2  1.000000  1.000000  1.000000

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(x)
scaler.transform(x)

array([[0.        , 0.        , 0.        ],
       [0.33333333, 0.16666667, 0.11111111],
       [1.        , 1.        , 1.        ]])

### 零-均值标准化

In [4]:
# 默认x.std(ddof=1) 是伪标准差
xScalaZeroMean = (x - x.mean()) / x.std(ddof=0) 
xScalaZeroMean

0         1         2
0 -1.069045 -0.889001 -0.827606
1 -0.267261 -0.508001 -0.579324
2  1.336306  1.397001  1.406930

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
scaler.transform(x)

array([[-1.06904497, -0.88900089, -0.82760589],
       [-0.26726124, -0.50800051, -0.57932412],
       [ 1.33630621,  1.3970014 ,  1.40693001]])

### 最小定标标准化

In [6]:
maxNum = np.abs(x).max()
num = np.log10(maxNum)
numCeil = np.ceil(num)
xScalaMin = x / 10 ** numCeil
xScalaMin

0     1     2
0  0.1  0.02  0.03
1  0.4  0.05  0.06
2  1.0  0.20  0.30

### 最大值标准化

In [7]:
from sklearn.preprocessing import MaxAbsScaler
scaler = MaxAbsScaler()
scaler.fit(x)
scaler.transform(x)

array([[0.1 , 0.1 , 0.1 ],
       [0.4 , 0.25, 0.2 ],
       [1.  , 1.  , 1.  ]])

## 注意:: 以上的自己实现的都是针对dataFrame的,如果是array的那么都会出错,因为dataFrame的聚合操作是针对每列的,而array的操作都是针对整个数组的

In [14]:
x = x.values
# 这样做是错误的
xScalaMinMax = (x - x.min()) / (x.max() - x.min())
xScalaMinMax

array([[0.        , 0.03448276, 0.06896552],
       [0.10344828, 0.13793103, 0.17241379],
       [0.31034483, 0.65517241, 1.        ]])

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(x)
scaler.transform(x)

array([[0.        , 0.        , 0.        ],
       [0.33333333, 0.16666667, 0.11111111],
       [1.        , 1.        , 1.        ]])